package entidades;
// Generated 13/05/2019 09:45:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String codigo;
     private String descripcion;
     private char estado;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id, String codigo, String descripcion, char estado) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Categoria(int id, String codigo, String descripcion, char estado, Set productos) {
       this.id = id;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.productos = productos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


