package entidades;
// Generated 13/05/2019 09:45:27 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Ventas ventas;
     private int cantidad;
     private BigDecimal subtotal;
     private int idVenta;
     private int idProducto;
     private String detalleVentacol;

    public Detalleventa() {
    }

	
    public Detalleventa(int id, Producto producto, Ventas ventas, int cantidad, BigDecimal subtotal, int idVenta, int idProducto) {
        this.id = id;
        this.producto = producto;
        this.ventas = ventas;
        this.cantidad = cantidad;
        this.subtotal = subtotal;
        this.idVenta = idVenta;
        this.idProducto = idProducto;
    }
    public Detalleventa(int id, Producto producto, Ventas ventas, int cantidad, BigDecimal subtotal, int idVenta, int idProducto, String detalleVentacol) {
       this.id = id;
       this.producto = producto;
       this.ventas = ventas;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.idVenta = idVenta;
       this.idProducto = idProducto;
       this.detalleVentacol = detalleVentacol;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getDetalleVentacol() {
        return this.detalleVentacol;
    }
    
    public void setDetalleVentacol(String detalleVentacol) {
        this.detalleVentacol = detalleVentacol;
    }




}


