package entidades;
// Generated 13/05/2019 09:45:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private String nombre;
     private double precio;
     private String marca;
     private Set detalleventas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int id, Categoria categoria, String nombre, double precio, String marca) {
        this.id = id;
        this.categoria = categoria;
        this.nombre = nombre;
        this.precio = precio;
        this.marca = marca;
    }
    public Producto(int id, Categoria categoria, String nombre, double precio, String marca, Set detalleventas) {
       this.id = id;
       this.categoria = categoria;
       this.nombre = nombre;
       this.precio = precio;
       this.marca = marca;
       this.detalleventas = detalleventas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


